[package]
name = "cf"
version = "0.1.0"
authors = ["Evgeny Proydakov <e.proydakov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "*" }
